name: tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
      - name: Build Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      - name: Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Maven Tests Result
          path: ${{ github.workspace }}/target/surefire-reports/TEST-TestSuite.xml
          reporter: java-junit
          fail-on-error: true
          java-version: 17
